# default number of workers to 4
web_workers: 4

# list of datasource connection info
data_sources:
  - username: "cryptobroker_api"
    password: "qVyNsY5VWNtbqM"
    schema: "cryptobroker"
    host: "45.33.102.234"
    port: 5432